# Generated by Django 5.2.1 on 2025-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
