# Generated by Django 5.2.1 on 2026-01-06 10:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0001_initial"),
        ("user_app", "0006_remove_user_address_remove_user_blood_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="bag_number",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="location",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="message",
        ),
        migrations.RemoveField(
            model_name="donationhistory",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="donationhistory",
            name="location",
        ),
        migrations.RemoveField(
            model_name="donationhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="fulfilled_bags",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.account",
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="required_bags",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="blood_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="posts_app.bloodrequest",
            ),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("closed", "Closed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donationhistory",
            name="donate_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="donationhistory",
            constraint=models.UniqueConstraint(
                fields=("donor", "blood_request"),
                name="one_donation_per_donor_per_request",
            ),
        ),
    ]
