# Generated by Django 5.2.1 on 2026-01-27 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0002_remove_bloodrequest_bag_number_and_more"),
        ("user_app", "0006_remove_user_address_remove_user_blood_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.location",
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="user_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_bags",
            field=models.PositiveIntegerField(),
        ),
    ]
