# Generated by Django 5.2.1 on 2025-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0002_bloodrequest_latitude_bloodrequest_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="user",
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester_phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
