# Generated by Django 5.2.1 on 2025-07-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0004_bloodrequest_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="user",
        ),
    ]
