# Generated by Django 5.2.1 on 2025-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
