# Generated by Django 5.2.1 on 2025-06-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_donner_adress_donationhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donner",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.RemoveField(
            model_name="donationhistory",
            name="donnor",
        ),
        migrations.DeleteModel(
            name="BloodGroup",
        ),
        migrations.DeleteModel(
            name="DonationHistory",
        ),
    ]
