# Generated by Django 5.2.1 on 2025-07-03 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_donner_blood_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Donner",
            new_name="Account",
        ),
    ]
