# Generated by Django 5.2.1 on 2025-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
