# Generated by Django 5.2.1 on 2025-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_user_blood_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="adress",
            new_name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
